#!/usr/bin/env bun

/**
 * Batch 3 Event Enrichment
 * Generates proper 400-word descriptions (380-420 words acceptable)
 */

import { readFileSync } from "fs";
import { join } from "path";
import { updateEventEnrichment } from "../src/db/database";

interface RawEvent {
  id: string;
  title: string;
  type: string;
  start_date: string;
  venue_name: string;
  genres: string;
  url: string;
  description: string;
}

// Track statistics
const stats = {
  total: 0,
  successful: 0,
  failed: 0,
  totalWords: 0,
  results: [] as Array<{ title: string; wordCount: number; status: string }>
};

function countWords(text: string): number {
  return text.trim().split(/\s+/).length;
}

// All 20 enriched descriptions - properly targeting 400 words each
const enrichments: Record<string, string> = {
  "9ef231201a8928f2": `Mass Culture returns to AUX Club on October 25th, bringing their distinctive brand of contemporary Greek rock alongside supporting acts Sidus and Kiva for a triple-bill showcase highlighting the current vitality of Greece's independent rock scene. This carefully curated lineup represents different facets of contemporary rock music being created in Athens right now, with each band contributing their unique perspective while sharing common values of musical integrity, authentic expression, and commitment to creating art rather than merely commercial product. The evening offers audiences an opportunity to experience multiple generations and approaches to rock within a single show, from Mass Culture's established presence to emerging artists still defining their sound.

Mass Culture has built their reputation over years of consistent touring, recording, and presence within Greece's alternative music community, developing a sound that honors rock music's fundamental energy and directness while incorporating elements reflecting contemporary Greek musical consciousness and current cultural concerns. Their approach balances accessibility that welcomes newcomers with depth that rewards longtime followers, featuring guitar-driven arrangements that range from atmospheric textures to powerful riffs, supported by tight rhythm section work providing both foundation and dynamic flexibility. Their lyrics address contemporary Greek experiences through personal lenses rather than abstract generalities, sung in Greek with conviction that transcends language barriers through emotional authenticity and musical intensity.

Sidus brings their own perspective to the bill, representing the continuing evolution of Greek rock with fresh energy while respecting the traditions established by previous generations. Their inclusion on this lineup suggests musical approaches that complement Mass Culture's aesthetic while offering distinct identity and artistic vision. Kiva rounds out the evening, completing a program that offers variety in sound and approach while maintaining cohesive quality standards and shared aesthetic values. The multi-band format creates natural pacing for the evening, with each act building energy toward the headliner while providing complete experiences in their own right rather than merely serving as warm-up acts.

AUX Club provides an ideal environment for this type of showcase, with sound systems designed specifically for guitar-driven rock music requiring clarity across frequency ranges and power that translates physical impact to audiences. The venue's reputation for supporting quality rock programming and commitment to providing proper technical support for performers ensures that each band's vision reaches audiences as intended. The intimate capacity creates atmosphere where performers and audiences share space in ways that larger venues cannot replicate, fostering direct connection and community feeling that defines alternative rock at its most authentic. For followers of contemporary Greek rock and those curious about what's happening beyond mainstream commercial music, this triple-bill offers substantial value and discovery opportunities.`,

  "f2038dca083c6ee7": `The Rasmus return to Greece on October 25th at Floyd, bringing their internationally recognized rock sound and over two decades of musical evolution to Athens for a concert celebrating both their greatest hits that defined alternative rock in the early 2000s and new material from their latest album demonstrating continued artistic vitality and relevance. This Finnish band achieved global recognition with songs like "In the Shadow" and "Guilty" that became anthems for a generation seeking rock music with emotional depth, melodic sophistication, and willingness to explore darker themes without losing accessibility or falling into pretentious art-rock territory. Their return to Greek stages represents a chance for longtime fans to reconnect with music that shaped their youth and for newer audiences to discover why The Rasmus remained influential long after their initial commercial peak.

The band's career trajectory spans multiple albums, each representing different phases of their artistic development while maintaining recognizable core elements—Lauri Ylönen's distinctive vocals with their melancholic yet powerful qualities, sophisticated songwriting that balances accessibility with depth, and production values that enhance rather than overwhelm the songs' emotional cores. Their early work established them as leaders in the European alternative rock scene, with melodic sensibilities drawing from both Finnish musical traditions and international influences ranging from British alternative rock to American grunge. Later albums have seen them evolve beyond the sound that initially brought fame, incorporating electronic elements, exploring more experimental arrangements, and addressing mature themes reflecting personal and collective experiences over years of touring, recording, and navigating the music industry's constant changes.

This Floyd performance promises a comprehensive set spanning their catalog, from beloved classics that audiences will sing along to with passionate recognition, to newer compositions from their latest album that demonstrate their continued creative vitality and refusal to simply repeat past successes. The live setting allows the band to unleash the full power of their arrangements beyond studio constraints, with extended instrumental sections, improvised moments, and the kind of between-song communication that reveals the personalities behind the music. Floyd's reputation as one of Athens' premier rock venues, with sound systems designed for guitar-driven music and atmosphere that respects both performers and audiences, makes it an ideal setting for this return performance.

For followers of early 2000s alternative rock, this concert offers nostalgic value beyond simple repetition of the past, demonstrating how bands that achieved success continue evolving while respecting their legacy. For those discovering The Rasmus for the first time, it provides introduction to music that influenced countless artists and defined an era.`,

  "b529915c42d43d4c": `Epic celebrates a decade of extraordinary parties with a special 10-year anniversary event at WE in Thessaloniki on October 25th, returning to the city where everything began in 2015 to mark this significant milestone with the community that has supported these legendary nights since their inception. This homecoming celebration represents more than just another party—it's a recognition of ten years of consistently exceptional electronic music programming, community building through shared experiences on countless dance floors, and Epic's role in shaping Thessaloniki's nightlife culture by maintaining uncompromising standards for music quality while creating inclusive environments where everyone feels welcome to lose themselves in sound and movement.

The ten-year journey from Epic's first events in 2015 to this anniversary celebration traces the evolution of electronic music culture in northern Greece, documenting how a concept focused on quality programming and respect for both music and audiences could build lasting community despite constantly changing trends and competition from commercial ventures prioritizing profit over artistic integrity. Epic has weathered challenges facing independent promoters everywhere—venue changes, economic uncertainties, evolving audience tastes—by remaining true to core values of musical quality, proper technical production, and treating audiences as intelligent participants rather than consumers. This anniversary event brings together elements that have defined Epic throughout the decade: resident DJs whose selections shaped Epic's sonic identity, special guests representing the evolution of their programming vision, and production values that create immersive environments where music takes center stage.

WE provides the perfect setting for this milestone celebration, with multiple rooms allowing diverse programming that can satisfy different moods and energy levels while maintaining Epic's cohesive aesthetic throughout the space. The venue's sophisticated sound systems, carefully designed lighting that enhances rather than overwhelms the music, and spatial configuration that prioritizes the dance floor experience make it an ideal partner for Epic's vision. The anniversary production includes special visual installations created specifically for this celebration, enhanced technical elements honoring ten years of innovation, and programming that spans Epic's history while looking toward the future.

For longtime Epic supporters, this anniversary represents both nostalgia and continuation—a chance to reconnect with friends made on past dance floors while creating new memories. For newer attendees, it offers insight into what makes Epic special and why it has endured when countless other party concepts have disappeared. This celebration embodies the community spirit that has always been Epic's foundation, proving that quality electronic music culture thrives when built on respect, authenticity, and love for the music itself.`,

  "146ec1c4ea664727": `Taki Tsan and DJ ALX bring their "Den Einai Kako Rap Party" (It's Not a Bad Rap Party) to Dexameni Project in Patras on Saturday, October 25th, delivering authentic Greek hip-hop culture to one of Greece's most vibrant cities beyond the Athens-Thessaloniki axis. This tour, presented by Rapnroll.gr, represents the continuing effort to bring quality hip-hop experiences to audiences throughout Greece rather than concentrating only in major metropolitan areas, demonstrating respect for hip-hop communities everywhere and recognition that passionate rap fans and meaningful scenes exist in cities often overlooked by touring artists and promoters focused only on major markets.

Taki Tsan stands as one of the most respected figures in Greek hip-hop, with a career spanning decades during which he has consistently represented hip-hop culture authentically, maintained artistic integrity despite commercial pressures, and contributed to building Greece's rap scene from underground beginnings to its current mainstream visibility. His approach combines technical MC skills developed through years of practice and performance, lyrical content addressing both personal experiences and broader social issues affecting Greek society, and deep respect for hip-hop's cultural foundations while remaining open to evolution and innovation. His continued touring and commitment to performing in diverse venues across Greece demonstrates understanding that hip-hop thrives through direct connection between artists and communities rather than distant celebrity relationships.

DJ ALX brings essential elements to this party, providing the musical foundation through skilled turntablism, expertly curated song selections spanning Greek hip-hop history and international influences, and the kind of technical DJ abilities that elevate performances beyond simple playlist playing. The partnership between MC and DJ creates the classic hip-hop format that honors the culture's essential elements while allowing for improvisation, crowd interaction, and spontaneous moments that make each show unique. The "Den Einai Kako" party concept suggests an unpretentious approach focused on good times, quality rap music, and community gathering without excessive production elements or artificial hype—just honest hip-hop culture presented authentically.

Dexameni Project in Patras has established itself as an important venue for alternative culture in western Greece, consistently programming quality events across genres while maintaining standards that respect both artists and audiences. For hip-hop heads in Patras and surrounding areas, this event offers a rare opportunity to experience one of Greek rap's pioneers live, celebrating hip-hop culture with authenticity and respect for the traditions while remaining firmly rooted in the present moment.`,

  "b7a983990075680e": `Omixli and Strafi take the stage together at Circus Entertainment Hub in Larissa on October 25th, uniting two significant names in Greek punk and alternative rock for an evening celebrating the raw energy, authentic emotion, and uncompromising spirit that defines punk rock at its most genuine. This pairing brings together bands representing different approaches within Greek alternative music while sharing common values of musical integrity, direct emotional expression, and commitment to creating art that matters beyond commercial considerations. The double-bill format creates natural synergy, with each band's energy building toward a comprehensive evening that showcases Greek punk and rock at their most vital and authentic.

Omixli has built their reputation within Greece's alternative music scene through consistently powerful performances, emotionally direct songwriting, and sound that honors punk's fundamental energy while incorporating elements reflecting contemporary Greek musical consciousness and current cultural concerns. Their music embraces punk's tradition of addressing challenging subjects without pretense or artifice, creating songs that connect with audiences through shared experiences and emotional honesty rather than commercial formulas or calculated image construction. The band's name—meaning "fog" in Greek—suggests music dealing with unclear situations, obscured vision, or the disorienting experiences of contemporary life, themes explored through powerful instrumentation and passionate vocal delivery that leaves no doubt about the emotional stakes involved.

Strafi brings their own punk energy and perspective to the evening, completing a program that offers variety in sound while maintaining cohesive quality standards and shared aesthetic values rooted in punk's fundamental principles. Their inclusion suggests a band that complements Omixli's approach while contributing distinct identity and artistic vision, creating dynamic interplay between sets and offering audiences diverse perspectives on contemporary Greek punk and alternative rock. The "Back on the Streets" subtitle hints at punk's origins in street culture, working-class expression, and music created outside official cultural institutions and commercial music industry structures.

Circus Entertainment Hub in Larissa provides an ideal environment for this type of punk rock showcase, with sound systems capable of delivering the power and clarity that guitar-driven music requires, capacity that creates intimate atmosphere without feeling cramped, and reputation for supporting quality alternative music programming that prioritizes artistic integrity over commercial considerations. For followers of Greek punk and alternative rock, this double-bill offers exceptional value with two accomplished bands sharing an evening. For those curious about what's happening in Greek alternative music beyond mainstream commercial sounds, it provides accessible introduction to artists creating genuine, uncompromising work that honors punk's traditions while remaining firmly rooted in present concerns.`,

  "f3f821dc8dea70d8": `Giorgis Manolakis brings traditional Cretan music to Theatre of the NO on October 25th, performing at Athens' English-speaking theatre venue in an intimate concert format that bridges Greek musical heritage and international audiences through the universal language of masterful musicianship and emotional authenticity. This performance features Manolakis on Cretan lyra—the three-stringed bowed instrument central to Crete's musical traditions—joined by Nikos Sidyrokastritis on percussion and Dimitris Tsekouras on double bass, creating a trio that honors traditional forms while demonstrating how heritage music can speak powerfully to contemporary audiences when performed with both deep knowledge and artistic vision refusing to treat tradition as museum piece.

The Cretan musical tradition that Manolakis represents extends back centuries, with roots in Byzantine musical practices, Venetian and Ottoman influences from Crete's complex history, and distinctly Cretan cultural identity shaped by the island's geography, historical experiences, and fierce independence. The lyra occupies a central place in this tradition, with its distinctive sound—simultaneously mournful and celebratory—providing the melodic foundation for traditional dances like pentozali and sousta, accompanying mantinades (improvised rhyming couplets commenting on life, love, and current events), and serving as the voice of Cretan cultural identity preserved through generations despite external pressures. Manolakis' mastery of this instrument represents years of study with elder musicians who carry traditional knowledge, combined with artistic vision that understands how to present this music to diverse audiences without compromising its essential character.

The ensemble format allows for rich musical dialogue, with Sidyrokastritis' percussion providing both rhythmic foundation for traditional dance forms and contemporary sensitivity to dynamics and texture, while Tsekouras' double bass adds harmonic depth and lower register support that enhances the lyra's melodic lines without overwhelming its distinctive voice. This combination honors traditional Cretan music while incorporating elements from jazz and contemporary acoustic music that reveal unexpected connections between musical traditions often treated as separate categories. Theatre of the NO's context as an English-speaking venue makes this performance accessible to Athens' international community alongside Greek audiences, demonstrating how deeply rooted cultural traditions can communicate across language barriers through musical excellence and emotional authenticity.

For lovers of traditional Greek music, world music, or anyone curious about how heritage forms remain vital when performed with both respect and artistic vision, this intimate concert offers extraordinary opportunities to experience Cretan music from a master musician committed to both preserving and evolving tradition.`,

  "e54a20218f1b1927": `Pyx Lax returns to VOX for their recurring Saturday night residency "Gia tis Palies Agapes" (For the Old Loves) starting October 25th, bringing one of Greek rock's most beloved and enduring bands back for another season of nostalgic celebration mixed with musical excellence and the kind of intergenerational appeal that defines truly significant artists. This series features special guests Giannis Zouganelis and Dimitris Starova joining the legendary band for performances that honor their extensive catalog while creating unique collaborative moments unavailable at typical concerts. The recurring Saturday format allows Pyx Lax to build momentum throughout the season, with each performance adding to an evolving narrative as regular attendees become part of a community united by shared musical love and memories associated with songs that have soundtracked their lives.

Pyx Lax occupies a unique position in Greek music history, having emerged in the late 1980s with a sound that bridged Greek musical sensibilities and international rock influences, creating songs that worked both as sophisticated rock compositions and as singalong anthems embraced across different demographics and generations. Their ability to craft melodies that stick in memory while maintaining musical sophistication, write lyrics in Greek that resonate emotionally without pretension, and deliver performances that balance professionalism with genuine passion has made them one of Greece's most consistently successful and respected rock bands across decades of changing trends and evolving music industry landscapes.

The "For the Old Loves" concept explicitly embraces nostalgia while avoiding its pitfalls through musical excellence that ensures performances transcend mere repetition of past glories. The inclusion of Zouganelis—himself an accomplished songwriter and performer with extensive solo career—and Starova adds dimension to the performances, creating opportunities for collaborative interpretations of beloved songs, guest appearances during each other's material, and musical dialogues between accomplished artists who respect each other's work. VOX provides an ideal setting for this residency, with its intimate capacity creating atmosphere where the connection between band and audience feels direct and personal, sound system designed for rock music's specific requirements, and reputation as one of Athens' premier venues for quality live music.

For longtime Pyx Lax fans, these Saturday nights offer reliable opportunities to reconnect with music that holds deep personal meaning and memories. For younger audiences discovering the band, it provides accessible introduction to essential Greek rock history in settings designed for celebration rather than formal appreciation, creating new memories and demonstrating why certain artists transcend generational boundaries.`,

  "48d038c42ceca572": `Lakis Papadopoulos, Giannis Giokarinis, Nikos Ziogalas, and Vasilis Kazoulis unite at Kyttaro Live for three special Saturday nights on October 4th, 11th, and 25th, bringing together four accomplished artists from Greek music's established generation for collaborative performances celebrating their extensive catalogs, shared musical history, and continuing creative vitality. This multi-artist format creates natural variety and pacing throughout each evening, with each performer contributing their distinctive voice, repertoire, and stage presence while creating opportunities for collaborative moments, musical dialogues, and unique interpretations that exist only in live performance contexts where accomplished artists can respond spontaneously to each other's contributions.

Each artist brings extensive individual accomplishment and distinctive aesthetic to this collaboration. Papadopoulos, Giokarinis, Ziogalas, and Kazoulis have each built careers spanning decades through consistent quality output, thoughtful artistic development, and ability to connect with audiences across different periods of Greek musical culture. Their coming together represents both celebration of individual achievements and recognition that collaboration between established artists creates something beyond what any single performer might achieve alone—musical dialogues revealing unexpected connections between different artistic voices, complementary energies creating dynamic performances, and collective experience that comes from years of professional musicianship at the highest levels.

The three-date format allows the collaboration to evolve over time, with each performance potentially varying based on what worked in previous shows, spontaneous decisions made in the moment, and the particular energy each audience brings. This creates value for attendees who might return for multiple nights, as each evening offers slightly different experiences while maintaining core quality and artistic vision. The October Saturday scheduling positions these shows as significant events worth planning around rather than casual weeknight entertainment, suggesting production values and artistic ambitions appropriate to the caliber of artists involved and the prestige of the venue hosting them.

Kyttaro Live occupies a special place in Athens' music culture, having established itself over decades as the venue where quality music receives proper presentation without commercial compromise or pretentious atmosphere excluding regular music lovers. The venue's sound system, maintained specifically for live performance's demanding requirements, ensures that vocal nuances and instrumental details reach audiences clearly. The intimate capacity creates direct connection between performers and audiences that enhances emotional impact and allows for the kind of subtle communication impossible in larger venues where distance creates psychological barriers.

For followers of Greek music who appreciate artistry, collaboration between accomplished musicians, and performances balancing professionalism with genuine passion, these three October Saturday nights at Kyttaro represent essential events offering both nostalgia and continuing artistic vitality from musicians still creating at high levels.`,

  "1135159437428225": `Eleni Dimou brings her live show to Kafetheatro on October 25th, presenting an evening of music described as deeply personal, where "the songs always tell the truth." This intimate performance at one of Athens' most charming small venues creates an environment where music becomes conversation between artist and audience, with Dimou's vocal presence and emotional directness connecting with listeners through shared human experiences and the kind of authentic expression that transcends language barriers and cultural differences. The Kafetheatro setting—combining cafe culture with focused entertainment—allows audiences to experience quality performance in relaxed surroundings that feel welcoming rather than intimidating, creating atmosphere conducive to genuine connection and emotional openness.

Dimou's approach to performance appears to embrace honesty and emotional authenticity as primary values, prioritizing genuine expression over technical display for its own sake or calculated image construction designed to appeal to commercial considerations. The statement that "songs always tell the truth" suggests an artist who views music as a vehicle for exploring and communicating authentic human experiences, emotions, and observations about life rather than as mere entertainment or commercial product. This philosophical approach aligns with traditions of singer-songwriters who use music as a form of personal expression and communication, creating work that resonates with audiences through shared recognition of universal human experiences—love, loss, joy, uncertainty, hope—presented without artifice or pretense that might create distance between performer and listener.

The "live" format emphasizes the importance of direct performance and real-time connection between artist and audience rather than relying on recorded material or electronic mediation. In live settings, subtle vocal nuances, spontaneous emotional moments, and direct eye contact create layers of communication unavailable through recordings or video documentation. Dimou's choice to perform at Kafetheatro rather than larger commercial venues suggests an artist who values intimacy and direct connection over mass appeal or commercial scale, prioritizing quality of experience over quantity of audience members and choosing venues where music can be heard with full attention rather than as background to social activity.

Kafetheatro's dual function as cafe and performance space creates unique atmosphere where audiences can enjoy refreshments while experiencing music, combining multiple pleasures—good music, comfortable surroundings, opportunities for conversation—into complete experiences rather than single-purpose outings. For those seeking alternatives to both impersonal club environments and overly formal concert halls, this performance offers accessible entry point to quality music presented honestly. Whether familiar with Dimou's work or discovering her for the first time, attendees can expect an evening where songs speak truth and emotional authenticity takes center stage.`,

  "b63f7ef682c0b4bd": `Iro performs at Caja de Musica on October 25th, bringing her distinctive voice to one of Athens' most respected intimate venues for art music and sophisticated acoustic performance. This evening celebrates entechno—the Greek art music tradition that emerged in the mid-20th century, combining elements from Greek folk traditions, Byzantine music, rebetiko urban song, and Western classical composition to create a distinctly Greek musical form that speaks to both intellectual appreciation and emotional engagement. Iro's performance represents a continuation of this tradition while bringing contemporary sensitivity and personal interpretive vision to material that spans multiple generations of Greek composers and poets who have shaped this genre.

Entechno occupies a unique position in Greek cultural life, representing music that demands both emotional engagement and intellectual appreciation, honoring Greek language's poetic possibilities, and addressing substantial themes through collaboration between composers and poets whose work explores Greek history, mythology, personal experience, political concerns, and philosophical questions. The tradition includes legendary figures like Mikis Theodorakis and Manos Hadjidakis who elevated Greek popular music to art form status, alongside subsequent generations who have continued evolving entechno while respecting its foundational principles. Iro's participation in this tradition suggests an artist who understands both the historical weight and continuing relevance of entechno, bringing technical vocal skills, interpretive intelligence, and emotional authenticity to performances that honor composers' intentions while revealing personal perspective.

Caja de Musica provides an ideal setting for experiencing entechno in proper conditions, with acoustic design that ensures vocal clarity without electronic amplification compromising natural sound quality, intimate capacity that creates direct connection between performer and audience, and atmosphere that supports focused listening while maintaining welcoming quality that makes art music accessible beyond academic circles or exclusive cultural elites. The venue's commitment to programming quality art music alongside other acoustic forms has made it a destination for discerning listeners seeking alternatives to mainstream entertainment, creating a community of regular attendees who value artistic substance and genuine musical communication.

The evening offers both intellectual engagement through entechno's sophisticated musical compositions and poetic texts addressing substantial themes, and emotional connection through Iro's interpretive abilities and the genre's fundamental commitment to human expression beyond mere technical display. For lovers of Greek art music, poetry set to music, or anyone curious about musical traditions that bridge popular and art music categories while maintaining artistic integrity, this performance promises an evening of musical and cultural substance that respects audience intelligence and emotional capacity.`,

  "a76c6cf397c72efd": `Violator presents a Depeche Mode Tribute Party at Temple on October 25th, with DJ set by Spyros Pagiatakis from En Lefko 87.7, live cover performances, special happenings, and an evening designed to immerse fans in the atmospheric, emotional, and sonic world of one of electronic music's most influential and enduring bands. This event goes beyond simple tribute night format by creating comprehensive experience combining recorded music played by a DJ who understands both Depeche Mode's extensive catalog and club dynamics, live musicians interpreting beloved songs, and theatrical elements that evoke the band's distinctive aesthetic. Temple's reputation for hosting themed events that become immersive experiences rather than simple DJ nights makes it ideal for this ambitious celebration.

Depeche Mode's influence on electronic music, alternative culture, and popular music broadly cannot be overstated, with a career spanning over four decades during which they pioneered the use of synthesizers and electronic production in pop contexts, explored darker themes of desire, power, spirituality, and human fragility that challenged mainstream pop's typical concerns, and created a distinctive sonic and visual aesthetic instantly recognizable across generations. Their evolution from early synthpop through increasingly sophisticated production and darker thematic material while maintaining melodic accessibility demonstrates artistic growth and refusal to simply repeat past successes. Songs like "Personal Jesus," "Enjoy the Silence," "Policy of Truth," and countless others have become cultural touchstones, their lyrics quoted in everyday conversations and their sounds sampled by artists across genres.

The party format combines Pagiatakis' DJ selections spanning Depeche Mode's extensive catalog—from early material on albums like "Speak & Spell" and "A Broken Frame" through their commercial peak with "Violator" and "Songs of Faith and Devotion," to more recent work demonstrating continued creative vitality—with live musicians covering beloved songs in ways that honor originals while bringing fresh energy and real-time performance. The "happenings" mentioned suggest theatrical elements, visual projections, costume elements, or interactive components that create atmosphere beyond simple music playback, evoking Depeche Mode's sophisticated visual aesthetic and the devotional fervor of their fanbase.

For devoted Depeche Mode fans, this party offers community connection with others who share appreciation for the band, opportunities to hear deep cuts alongside radio hits, and environment celebrating their musical love. For those casually familiar with their biggest songs, it provides accessible introduction to their broader catalog and understanding of why they remain influential decades after initial emergence. The combination of DJ set, live performances, and atmospheric elements creates complete experience that honors Depeche Mode's artistic vision while celebrating their enduring impact.`,

  "491c70521aac6d7f": `Dimitris Zervoudakis and Spyros Grammenos unite at Stavros tou Notou's main stage on October 25th, bringing two distinctive voices from Greek art music together for an evening that promises sophisticated musical dialogue, interpretive depth, and the kind of collaborative magic that happens when accomplished artists share space with mutual respect and complementary aesthetics. This pairing creates natural synergy, with each performer's individual strengths enhancing the other's contributions while their combined presence offers variety in vocal color, interpretive approach, and repertoire selection that makes for richer programming than solo concerts might provide.

Both Zervoudakis and Grammenos have built reputations within Greek art music circles through consistent quality, thoughtful repertoire choices, and vocal abilities serving music rather than merely showcasing technique. Their appearances at Stavros tou Notou—Athens' legendary venue for quality art music that has provided home for several generations of Greece's finest performers—signals serious artistic intent and suggests an evening designed for audiences who value substance over superficial entertainment. The main stage designation indicates full production values and recognition of these artists' significance within Greek musical culture.

The art music tradition they represent draws from diverse sources—folk melodies from various Greek regional traditions, Byzantine chant influences, rebetiko's urban poetry and modal sophistication, and art song traditions from Western classical music—synthesized into distinctly Greek musical forms that honor language's poetic possibilities and address substantial themes. The collaboration between two accomplished male vocalists creates opportunities for harmonic singing, call-and-response patterns, contrasting interpretations of similar material, and musical conversations impossible in solo contexts. Their combined repertoire likely spans multiple generations of Greek composers whose work defines entechno and related art music forms, from established classics that audiences recognize and love to lesser-known compositions deserving wider appreciation.

Stavros tou Notou's main stage provides ideal conditions for experiencing art music's nuances, with acoustics refined through decades of hosting performances ensuring vocal clarity, intimate capacity creating direct connection between performers and audiences, and atmosphere respecting both artists' needs and audiences' intelligence. For lovers of Greek art music, vocal artistry, and thoughtful interpretation of sophisticated material, this collaborative evening offers exceptional value with two accomplished artists sharing an evening and creating something greater than either might achieve alone.`,

  "162f7ecb3e0086df": `Parathyra me Thea (Windows with a View) performs at Stavros tou Notou Club on October 25th, bringing their rock sound to the intimate club space within Athens' legendary music venue complex. The band's evocative name suggests music that offers perspectives, reveals what might otherwise remain hidden, or provides vantage points for viewing life from different angles—metaphorical windows opening onto insights and observations expressed through rock music's emotional directness and sonic power. This appearance at one of Greek rock's most historically significant venues represents an important step for any band working within Greece's alternative music scene, performing on a stage where countless significant Greek rock acts have established themselves over decades.

The Stavros tou Notou Club—distinct from the venue's main stage and Plus room—has become known for presenting rock music that prioritizes authenticity and musical integrity over commercial considerations, providing a platform for both established acts seeking intimate settings and emerging bands building their following through consistent quality performances and word-of-mouth reputation. The space's design creates atmosphere where rock music's essential elements—direct emotional communication, physical energy, audience-performer connection—can flourish without excessive production elements or artificial hype that might distract from the music itself. The Club's sound system, specifically maintained for rock music's demanding requirements of clarity across frequency ranges and power that translates into physical impact, ensures that performances reach audiences as artists intend.

Parathyra me Thea's inclusion in Stavros tou Notou's programming suggests a band that has earned respect within Athens' alternative music community through previous performances, recorded work, or reputation that precedes them. The venue's selective booking policy means that bands performing there have demonstrated musical ability, artistic vision, or both in ways that meet the venue's standards built over decades of presenting quality rock music. The intimate Club setting allows audiences to experience rock music with immediacy impossible in larger venues where distance creates psychological barriers between performers and listeners, making for intense experiences where individual audience members feel personally addressed by performances.

For followers of Greek rock who appreciate authentic expression and musical integrity, this performance offers a chance to discover or reconnect with a band whose name alone suggests thoughtful approach to songwriting and performance. Whether familiar with Parathyra me Thea's previous work or discovering them for the first time, attendees can expect an evening of honest rock music that opens windows onto new perspectives and demonstrates the continuing vitality of Greece's alternative music scene.`,

  "2a0846594661f5a0": `Lefteris Eleftheriou, Eleni Karakasi, and Alkiviadis Konstantopoulos present "Tragouda Mou Fthinoporo" (Sing to Me, Autumn) at Stavros tou Notou Plus on October 25th, creating an evening that explores autumn's particular emotional resonance, metaphorical richness, and the season's long association with Greek art music and poetry. This collaboration brings together three accomplished performers with complementary aesthetics for a program celebrating autumn not just as meteorological season but as state of mind, emotional territory, and rich source of imagery for Greek poets and composers who have found in autumn's characteristics—falling leaves, changing light, harvest completion, approaching winter—metaphors for life's transitions, aging, loss, acceptance, and beauty found in impermanence.

Autumn occupies a special place in Greek cultural imagination and artistic expression, appearing frequently in art music repertoires through songs addressing the season's melancholic beauty, its position between summer's vitality and winter's darkness, and its associations with maturity, harvest, and preparation for difficult times ahead. The season's visual beauty—golden light, warm colors, comfortable temperatures after summer's intensity—combines with awareness of transience and approaching cold to create complex emotional territory that Greek composers and poets have explored through countless works. This program likely draws from this rich tradition while potentially including contemporary compositions continuing autumn's artistic associations.

The three-performer format creates natural variety in vocal colors, interpretive approaches, and energy that keeps programs engaging through contrasts and complementary qualities. Eleftheriou, Karakasi, and Konstantopoulos each bring individual strengths to collaborative performances, with opportunities for solo showcases highlighting each artist's distinctive voice and aesthetic, duets and trios creating harmonic richness and musical dialogues impossible in solo contexts, and ensemble moments where three voices unite in shared interpretations. Their combined repertoire choices likely balance familiar autumn-themed classics that audiences recognize and appreciate alongside lesser-known compositions deserving wider attention.

Stavros tou Notou Plus provides intimate setting ideal for art music's nuances, with acoustic design ensuring vocal clarity, capacity creating direct connection between performers and audiences, and atmosphere that supports focused listening while maintaining welcoming quality. For lovers of Greek art music, seasonal programming that engages with deeper meanings beyond simple entertainment, and vocal artistry that serves sophisticated material, this autumn-themed evening promises both emotional resonance and musical substance that speaks to universal human experiences through specifically Greek artistic traditions.`,

  "368c7859bad021a9": `Vasilis Paiteris and Sabrina present "Nychtes Magikes" (Magic Nights) at Gyalino Mousiko Theatro on October 25th, bringing two established names from Greek popular music together for an evening of entertainment, performance spectacle, and the kind of polished showmanship that characterizes Greek nightlife at its most professional and glamorous. This pairing represents strategic collaboration between complementary performers whose combined appeal promises an evening balancing Paiteris' distinctive presence and Sabrina's vocal abilities and stage charisma, creating variety in energy and approach while maintaining consistently high production values throughout the performance.

Paiteris brings extensive experience and distinctive identity within Greek entertainment to this collaboration, with career built on crafting memorable melodies, delivering polished performances, and understanding what audiences seek in complete entertainment experiences beyond simple concert formats. His repertoire spans multiple styles within Greek popular music, demonstrating versatility and ability to connect with audiences across different demographics and preferences. Sabrina adds her own vocal strengths, performance style, and star quality to the evening, creating opportunities for collaborative moments, contrasting solo showcases, and dynamic interplay between two performers with complementary energies and aesthetics.

The "Magic Nights" concept promises theatrical presentation, visual elements, production values, and carefully crafted show structure that creates complete entertainment experience rather than simple concert format. This suggests professional choreography enhancing performance without overwhelming musical elements, lighting design that creates atmosphere and excitement, costume changes adding visual interest, and show pacing that maintains energy and audience engagement throughout the evening. Gyalino Mousiko Theatro provides appropriate setting for this type of production, with stage capabilities supporting elaborate presentations, sound systems ensuring both vocal clarity and musical impact, and capacity creating atmosphere suited to professional entertainment while maintaining intimacy that keeps audiences connected to performances.

The venue's "glass music theatre" identity suggests both architectural distinction and commitment to hosting quality entertainment in visually distinctive spaces that enhance experiences through environmental design. Its programming history of hosting established artists from Greek popular music and its reputation for production values matching performer caliber make it an ideal partner for "Magic Nights" and the kind of professional entertainment that Paiteris and Sabrina represent.

For fans of Greek popular music seeking complete entertainment experiences with production values, professional performance, and the magic that happens when accomplished artists share stages, this evening promises memorable moments and quality entertainment designed to create special nights worth remembering.`,

  "f4304c17f9292776": `ATH DNB UNITY presents Cause 4 Concern from the UK at AUX Club on October 25th, bringing one of drum and bass music's most respected and influential production duos to Athens for an evening of cutting-edge electronic music that honors the genre's rich history while pushing toward its future possibilities. This event represents a significant moment for Athens' drum and bass community, offering rare opportunity to experience internationally recognized artists whose production work has shaped the genre's evolution, influenced countless other producers, and defined what sophisticated, forward-thinking drum and bass sounds like when created without compromise or commercial dilution.

Cause 4 Concern—comprised of producers Sean Moody and Chris Mace—have been integral to drum and bass evolution since the mid-1990s, with production work spanning the genre's various sub-styles from atmospheric liquid funk to harder-edged tech-step and neurofunk while maintaining recognizable aesthetic characterized by meticulous production quality, sophisticated sound design, and musical sensibility that elevates drum and bass beyond simple dancefloor functionality into artistically credible electronic music. Their DJ sets draw from deep knowledge of the genre's history, extensive personal production catalog, and current releases pushing boundaries, creating musical journeys that satisfy both longtime drum and bass heads familiar with obscure classics and newer fans discovering the genre's depth and diversity.

The ATH DNB UNITY series has established itself as Athens' premier platform for quality drum and bass programming, consistently bringing international artists alongside talented local DJs for events that prioritize music quality and proper presentation over superficial club elements or commercial considerations. This commitment to authentic drum and bass culture has built community of dedicated followers who understand and appreciate the genre's technical and artistic dimensions, creating atmosphere at Unity events where music receives proper respect and attention rather than serving as mere background to social activity.

AUX Club provides ideal environment for drum and bass performance, with sound system capabilities essential for the genre's demanding frequency range requirements—deep sub-bass felt physically, crisp high-end percussion maintaining clarity at high volumes, and overall power that translates drum and bass's energy into visceral physical experience. The venue's commitment to quality electronic music programming and its reputation within both local and international electronic music communities make it the natural home for Unity events and visiting artists like Cause 4 Concern.

For drum and bass enthusiasts and electronic music fans who appreciate the genre at its most sophisticated and uncompromising, this Saturday night offers an essential experience with legendary producers demonstrating why drum and bass continues evolving and inspiring new generations decades after its emergence from UK rave culture.`,

  "35e04e004aa29859": `VLCT Clubnight featuring Basswell and William Luck takes over Oddity Club on October 25th for an evening of hard kicks, dynamic basslines, and dark energy that characterizes techno and electronic music at its most intense and uncompromising. This Velocity edition brings together DJs and producers known for pushing boundaries within harder electronic styles, creating sonic experiences that demand full engagement and surrender to the music's physical impact and hypnotic qualities. Oddity Club's reputation for hosting serious electronic music events and its technical capabilities make it ideal for this type of programming that prioritizes music quality and proper presentation over superficial club elements or commercial considerations.

The harder end of the electronic music spectrum that VLCT programming represents embraces techno and related genres at their most aggressive and uncompromising, with production aesthetics favoring distorted kicks that hit like physical punches, basslines that rumble through your chest creating visceral responses, and dark atmospheric elements that create tension and intensity rather than uplifting euphoria or accessible melodicism. This approach speaks to audiences seeking electronic music that challenges rather than comforts, that demands attention rather than serving as pleasant background, and that creates immersive experiences through sustained intensity and commitment to the music's transformative potential when experienced at proper volume with full attention.

Basswell and William Luck bring their respective production skills and DJ abilities to this Velocity edition, each contributing their perspective on contemporary hard techno, industrial influences, and darker electronic sounds while maintaining coherent aesthetic throughout the evening's programming. Their sets likely feature both established tracks from the harder techno canon and cutting-edge new productions pushing genre boundaries, creating balance between familiar elements that unite the dance floor through shared recognition and forward-thinking material that challenges and expands expectations. The collaboration creates natural progression through the night, with each DJ building on the previous set's energy while contributing distinct character and approach.

Oddity Club has established itself within Athens' electronic music scene as venue willing to program more aggressive and uncompromising electronic styles often overlooked by clubs seeking broader commercial appeal, creating space for hard techno, industrial, and related genres to flourish and build dedicated communities. The venue's sound system capabilities—essential for delivering the bass weight and overall power these styles demand—and its atmosphere prioritizing music over social performance make it ideal for Velocity programming and audiences seeking serious electronic music experiences.

For hard techno enthusiasts and electronic music fans who appreciate intensity, sonic aggression used as artistic tool, and music that creates physical and psychological impact through commitment to its aesthetic without compromise, this Saturday night promises an uncompromising journey through electronic music's darker territories.`,

  "85cd5afdbccfe9a6": `EDEN presents Apparat at Athens Conservatoire on Sunday, October 26th, bringing one of electronic music's most thoughtful and artistically credible producers to a venue that bridges classical music tradition and contemporary sound in perfect alignment with Apparat's aesthetic approach. This rare Sunday afternoon-to-evening event—running from 17:30 to midnight under the motto "Sundays Are for Lovers"—features Apparat alongside special guests NIGHT Manoeuvres and JAY JAY, creating a comprehensive electronic music experience in the Conservatoire's unique setting that honors both musical history and contemporary innovation. The unconventional timing and venue choice signal an event conceived as artistic experience rather than typical club night, appealing to audiences seeking electronic music that engages intellectually while moving emotionally.

Apparat—the project of German producer Sascha Ring—has built international reputation through electronic music that refuses easy categorization, incorporating elements from techno, ambient, neo-classical, and experimental composition while maintaining cohesive artistic vision characterized by emotional depth, production sophistication, and musical intelligence. His work often features live instrumentation alongside electronic elements, human vocals exploring vulnerability and longing, and compositional approaches drawing from both club music's rhythmic foundations and classical music's structural complexity and attention to thematic development. Albums like "The Devil's Walk" and "LP5" demonstrate his ability to create electronic music that works both as background for introspective listening and as material for live performance that becomes immersive experience.

The Athens Conservatoire setting adds layers of meaning to this performance, with the venue's associations with classical music education, rigorous musical training, and cultural preservation creating interesting dialogue with electronic music's experimental nature and forward-looking aesthetics. This choice suggests recognition that electronic music has matured into art form deserving presentation in venues traditionally reserved for classical and art music, while electronic music's embrace demonstrates that distinctions between contemporary and traditional musical forms need not be rigid boundaries. NIGHT Manoeuvres and JAY JAY as special guests ensure full programming spanning afternoon into night, creating extended experience allowing audiences to surrender fully to musical immersion.

For Apparat fans and electronic music enthusiasts who appreciate artistry, compositional sophistication, and emotional depth alongside technical production excellence, this Sunday event offers rare opportunity to experience one of electronic music's most respected artists in Athens' unique venue that honors both tradition and innovation. The Sunday afternoon timing creates alternative to typical Saturday night club experiences, appealing to those seeking electronic music in context supporting focused listening.`,

  "4d0681f3bd48ab4c": `Middle Earth brings their "ROCKSTARS" tour to Cafe Santan in Volos on October 26th, joined by special touring guests Tight Spot for an evening celebrating rock music's enduring vitality, raw energy, and ability to create community through shared sonic experiences. This double-bill format showcases contemporary Greek rock through two bands representing dedication to the genre's fundamental values—authentic expression, musical integrity, sonic power—while demonstrating that rock music continues evolving and inspiring new artists and audiences despite decades of critics declaring its death. The Cafe Santan setting provides appropriate environment for this type of rock performance, combining venue functionality with grassroots authenticity characteristic of rock culture at its most genuine.

Middle Earth has built their reputation within Greece's rock community through consistent touring, recording that captures their live energy, and commitment to creating music honoring rock traditions while remaining firmly rooted in present rather than merely recreating past sounds. The "ROCKSTARS" tour title suggests both ironic commentary on rock mythology and genuine celebration of what makes rock music special—its ability to create moments of transcendence through volume, energy, and collective experience where performers and audiences unite in shared purpose. Their approach likely balances melodic accessibility that welcomes newcomers with instrumental sophistication and dynamic range that rewards longtime followers, featuring guitar work spanning atmospheric textures to powerful riffs, supported by rhythm section providing both foundation and flexibility.

Tight Spot's inclusion as touring support creates natural synergy, with their participation indicating complementary aesthetic and shared values rather than merely filling opener slot. The "tour" designation suggests coordinated multi-date run across different cities rather than isolated one-off performance, demonstrating commitment to building community through repeated exposure and creating opportunities for audiences in different locations to experience quality rock music. This approach reflects understanding that sustainable music scenes develop through consistent presence, word-of-mouth reputation, and direct connection between artists and audiences rather than commercial hype or media coverage.

Cafe Santan in Volos has established itself as important venue for alternative culture in central Greece, consistently programming quality events across genres while maintaining standards respecting both artists receiving proper technical support and audiences trusted to appreciate adventurous music. For rock enthusiasts in Volos and surrounding areas, this double-bill offers exceptional value with two bands sharing evening and likely appearing together for collaborative moments creating unique experiences. Whether longtime Middle Earth followers or discovering them for first time, attendees can expect genuine rock music demonstrating the genre's continuing vitality when performed with integrity and passion.`,

  "7747a93fa20ecf13": `Middle Earth's "ROCKSTARS" tour continues with Tight Spot at Cafe Santan in Volos on October 26th, bringing two committed rock bands to one of central Greece's most important venues for alternative music in an evening celebrating rock's enduring ability to create community, express authentic emotion, and deliver powerful sonic experiences that remind us why the genre has inspired generations despite constantly being declared dead by critics and trend-watchers. This tour stop represents the bands' commitment to reaching audiences throughout Greece rather than concentrating only in Athens and Thessaloniki, demonstrating respect for rock communities everywhere and recognition that passionate music lovers and meaningful scenes exist in cities often overlooked by touring artists focused on major markets.

The "ROCKSTARS" tour concept embraces both the mythology surrounding rock music—its associations with rebellion, authenticity, living life intensely—and the reality that creating and performing rock music in today's commercial landscape requires genuine dedication rather than expectation of fame or financial success. Middle Earth's approach appears to honor rock traditions while avoiding nostalgic recreation of past sounds, creating music that references the genre's rich history while remaining firmly rooted in contemporary concerns and current sonic possibilities. Their live performances are likely characterized by energy that can't be replicated in studio recordings, with dynamics ranging from controlled quieter passages building tension to explosive releases providing cathartic satisfaction, and direct communication with audiences that makes rock concerts feel like communal experiences rather than passive consumption.

Tight Spot's consistent presence throughout the tour creates opportunities for musical rapport developing over multiple performances, with each band learning from the other's approaches and potentially incorporating collaborative moments that make each show unique. The tour format allows performances to evolve as bands grow more comfortable with material and venues, discover what resonates with different audiences, and respond to feedback both explicit and implicit from listeners investing their time, money, and emotional energy in attending shows. This creates value for audiences who might see multiple tour stops, as each performance offers slightly different energy while maintaining core artistic vision.

Cafe Santan provides grassroots authenticity and proper technical capabilities for rock music requiring clarity across frequency ranges and power translating into physical impact. For rock fans in Volos and central Greece seeking authentic experiences with bands prioritizing musical integrity over commercial considerations, this tour stop offers essential evening demonstrating rock's continuing vitality when performed with commitment, passion, and respect for tradition balanced with contemporary relevance.`
};

// Process all events
async function processAll() {
  const batchPath = join(import.meta.dir, "../data/enrichment-batches/batch-3-of-13.json");
  const events: RawEvent[] = JSON.parse(readFileSync(batchPath, "utf-8"));

  stats.total = events.length;

  console.log("🎵 Processing Batch 3 Event Enrichment (20 events)");
  console.log("━".repeat(60));

  for (const event of events) {
    const enrichedDescription = enrichments[event.id];

    if (!enrichedDescription) {
      stats.failed++;
      stats.results.push({
        title: event.title,
        wordCount: 0,
        status: "❌ No enrichment found"
      });
      console.log(`❌ ${event.title}`);
      console.log(`   Status: No enrichment found`);
      console.log("");
      continue;
    }

    const wordCount = countWords(enrichedDescription);
    const aiContext = {
      enriched: true,
      wordCount,
      enrichedAt: new Date().toISOString(),
      batch: 3
    };

    try {
      const success = updateEventEnrichment(event.id, enrichedDescription, aiContext);

      if (success) {
        stats.successful++;
        stats.totalWords += wordCount;
        stats.results.push({
          title: event.title,
          wordCount,
          status: "✅ Success"
        });
        console.log(`✅ ${event.title}`);
        console.log(`   Words: ${wordCount} | Status: Success`);
      } else {
        stats.failed++;
        stats.results.push({
          title: event.title,
          wordCount: 0,
          status: "❌ Database update failed"
        });
        console.log(`❌ ${event.title}`);
        console.log(`   Status: Database update failed`);
      }
    } catch (error) {
      stats.failed++;
      stats.results.push({
        title: event.title,
        wordCount: 0,
        status: `❌ Error: ${error}`
      });
      console.log(`❌ ${event.title}`);
      console.log(`   Error: ${error}`);
    }
    console.log("");
  }

  // Final summary
  console.log("━".repeat(60));
  console.log("📊 BATCH 3 PROCESSING SUMMARY");
  console.log("━".repeat(60));
  console.log(`Total events processed: ${stats.successful + stats.failed}/${stats.total}`);
  console.log(`Successfully enriched: ${stats.successful}`);
  console.log(`Failed: ${stats.failed}`);
  console.log(`Total words generated: ${stats.totalWords.toLocaleString()}`);
  console.log(`Average words per description: ${Math.round(stats.totalWords / stats.successful)}`);
  console.log("━".repeat(60));

  // Detailed results
  console.log("\n📋 DETAILED RESULTS:");
  console.log("━".repeat(60));
  for (const result of stats.results) {
    console.log(`${result.status} | ${result.title}`);
    if (result.wordCount > 0) {
      console.log(`   ${result.wordCount} words`);
    }
  }
}

processAll().catch(console.error);
