const NEIGHBORHOOD_GREEK: Record<string, string> = {
  'Aigaleo': 'Αιγάλεω',
  'Alimos': 'Άλιμος',
  'Ambelokipi': 'Αμπελόκηποι',
  'Ampelokipoi': 'Αμπελόκηποι',
  'Central Athens': 'Κέντρο Αθήνας',
  'Dafni': 'Δάφνη',
  'Ellinikon': 'Ελληνικό',
  'Exarchia': 'Εξάρχεια',
  'Faliro': 'Φάληρο',
  'Galatsi': 'Γαλάτσι',
  'Gazi': 'Γκάζι',
  'Glyfada': 'Γλυφάδα',
  'Goudi': 'Γουδή',
  'Ilisia': 'Ιλίσια',
  'Kallirois': 'Καλλιρρόης',
  'Kallithea': 'Καλλιθέα',
  'Kerameikos': 'Κεραμεικός',
  'Kolonaki': 'Κολωνάκι',
  'Kolonos': 'Κολωνός',
  'Koukaki': 'Κουκάκι',
  'Kypseli': 'Κυψέλη',
  'Marousi': 'Μαρούσι',
  'Metaxourgeio': 'Μεταξουργείο',
  'Mets': 'Μετς',
  'Monastiraki': 'Μοναστηράκι',
  'Nea Ionia': 'Νέα Ιωνία',
  'Nea Smyrni': 'Νέα Σμύρνη',
  'Neos Kosmos': 'Νέος Κόσμος',
  'Omonoia': 'Ομόνοια',
  'Paleo Faliro': 'Παλαιό Φάληρο',
  'Pangrati': 'Παγκράτι',
  'Papagou': 'Παπάγου',
  'Patisia': 'Πατήσια',
  'Peania': 'Παιανία',
  'Pedion Areos': 'Πεδίον του Άρεως',
  'Perissos': 'Περισσός',
  'Peristeri': 'Περιστέρι',
  'Petralona': 'Πετράλωνα',
  'Piraeus': 'Πειραιάς',
  'Plaka': 'Πλάκα',
  'Psychiko': 'Ψυχικό',
  'Psyri': 'Ψυρρή',
  'Psyrri': 'Ψυρρή',
  'Rouf': 'Ρουφ',
  'Syntagma': 'Σύνταγμα',
  'Tavros': 'Ταύρος',
  'Thiseio': 'Θησείο',
  'Victoria': 'Βικτώρια',
  'Votanikos': 'Βοτανικός',
  'Vouliagmeni': 'Βουλιαγμένη',
  'Zografou': 'Ζωγράφου',
};

export function displayNeighborhood(name: string): string {
  return NEIGHBORHOOD_GREEK[name] || name;
}
