#!/usr/bin/env bun

/**
 * Batch 2 Event Enrichment - Final Version
 * Generates proper 400-word descriptions (380-420 words acceptable)
 */

import { readFileSync } from "fs";
import { join } from "path";
import { updateEventEnrichment } from "../src/db/database";

interface RawEvent {
  id: string;
  title: string;
  type: string;
  start_date: string;
  venue_name: string;
  genres: string;
  url: string;
  description: string;
}

// Track statistics
const stats = {
  total: 0,
  successful: 0,
  failed: 0,
  totalWords: 0,
  results: [] as Array<{ title: string; wordCount: number; status: string }>
};

function countWords(text: string): number {
  return text.trim().split(/\s+/).length;
}

// All 20 enriched descriptions - properly targeting 400 words each
const enrichments: Record<string, string> = {
  "7cc720580231da03": `Chrysiida Gkagkouti returns with her full band to present "I Megali Gorgona" (The Great Mermaid), a tour that promises to be one of the most compelling rock music experiences of the season. Known for her powerful stage presence and distinctive voice that bridges alternative rock with Greek musical sensibilities, Gkagkouti has built a reputation as one of the most authentic voices in contemporary Greek rock. This multi-venue tour brings her intimate yet explosive sound to stages across Greece, offering audiences a chance to experience the raw energy that has made her a cult favorite among those seeking music with genuine artistic integrity and emotional depth.

The show centers around tracks from her latest work, exploring themes of transformation, resilience, and the mysterious allure of the sea through the lens of Greek mythology reimagined for modern times. Gkagkouti's full band setup amplifies the intensity of her compositions, with driving guitar work that ranges from delicate fingerpicking to powerful distorted riffs, dynamic bass lines that provide both melodic counterpoint and solid foundation, and percussion that echoes both Western rock traditions and Greek folk rhythms. The musical arrangements showcase her ability to craft songs that are simultaneously accessible and artistically ambitious, with lyrics that move between personal introspection and broader cultural commentary, sung in Greek with poetry that resonates beyond language barriers.

Each performance creates an immersive atmosphere where rock energy meets theatrical presentation. The stage design incorporates visual elements inspired by Greek maritime mythology, creating a compelling backdrop for the musical journey without overwhelming the music itself. Gkagkouti's interaction with her band members creates moments of improvisation and raw musical dialogue that make each show unique, while maintaining the core integrity of the compositions that fans have come to love. The lighting design enhances the emotional arcs of the songs, moving from stormy intensity to moments of quiet reflection that mirror the sea's changing moods and the album's thematic concerns.

For rock enthusiasts and those who appreciate music that bridges cultural traditions with contemporary sound, this tour represents an opportunity to witness an artist at the height of her creative powers. The venues selected for the tour provide intimate settings that enhance the connection between performers and audience, creating memorable experiences beyond typical concert formats. Whether you're familiar with Gkagkouti's previous work or discovering her music for the first time, "I Megali Gorgona" promises an evening of powerful music that resonates on multiple levels, challenging and rewarding listeners in equal measure.`,

  "43444e29d467f322": `The Epic Party celebrates a decade of memorable nights at Circus Entertainment Hub in Larissa, marking ten years of bringing exceptional electronic music experiences to northern Greece. This milestone celebration returns Epic to Larissa after an extended absence, reuniting the community that has supported these events since their inception and introducing a new generation to what has made Epic such an enduring presence in Greek nightlife. The venue's reputation for outstanding sound systems, multi-room configurations, and atmospheric lighting makes it the perfect setting for this anniversary celebration, promising an epic party that honors the past while looking toward the next decade of innovation.

Over the past ten years, Epic has established itself as a cornerstone of Larissa's nightlife scene, consistently delivering quality electronic music programming that ranges from techno and house to more experimental electronic sounds and occasional crossovers with other dance music genres. The anniversary event brings together resident DJs who have shaped Epic's sound over the years, along with special guest performers who represent the evolution of electronic music culture in Greece. This carefully curated lineup ensures a musical journey through the sounds that have defined Epic's decade-long history, from the early days of intimate warehouse parties to today's sophisticated production values.

The celebration transforms Circus Entertainment Hub into an immersive party environment, with production values that elevate the experience beyond typical club nights. Special visual installations created specifically for the anniversary, enhanced lighting design that responds to the music's energy, and carefully crafted sound programming across multiple rooms create an atmosphere that honors Epic's commitment to quality entertainment and respect for the music. The venue's multiple spaces allow for varied musical programming throughout the night, offering attendees different sonic experiences while maintaining the cohesive Epic aesthetic that loyal fans recognize immediately.

For long-time Epic supporters, this anniversary represents a homecoming and a chance to reconnect with friends and moments from the past decade of nights that created lasting memories. For newer attendees, it offers insight into what has made Epic such an enduring presence in Greek nightlife despite constantly evolving trends and competition. The event embodies the spirit of celebration and community that has always been at Epic's core, creating shared experiences through music that transcend individual performances and remind everyone why they fell in love with electronic music culture in the first place.`,

  "ca78f5aa4395c54f": `Eftyhia Mitritsa performs at the Museum of Musical Instruments "Thyrathen," creating an intimate evening where art music meets the historic charm and unique acoustic properties of one of Athens' most distinctive cultural spaces. This venue, dedicated to preserving and celebrating musical instruments from various traditions, historical periods, and geographical origins, provides an extraordinary acoustic environment that enhances the nuanced qualities of art music performance in ways that conventional concert halls cannot replicate. Mitritsa's appearance here represents a perfect match between artist, carefully chosen repertoire, and setting, promising an experience that transcends conventional concert formats and creates something closer to a musical conversation.

The museum's collection of historical and contemporary instruments creates both a visual and contextual backdrop that enriches the musical experience on multiple levels. Thyrathen's commitment to musical heritage, education, and the preservation of instrumental traditions makes it more than just a performance venue—it's a space where music history comes alive through both its carefully curated exhibits and thoughtfully programmed live performances. The intimate scale of the museum's performance area, designed to accommodate smaller audiences in proximity to the performers, creates a direct connection between Mitritsa and her audience that allows for the subtle dynamics, micro-expressions, and expressive qualities of art music to be fully appreciated without electronic amplification interfering with natural acoustic properties.

Mitritsa's musical approach draws from diverse influences within the art music tradition, creating programs that balance technical sophistication with emotional accessibility and interpretive depth. Her performances are known for thoughtful repertoire selection that often includes works by both established composers from the classical canon and contemporary creators pushing the boundaries of art music, offering audiences fresh perspectives on familiar works alongside discoveries of lesser-known compositions. The acoustic properties of Thyrathen's performance space, shaped by the presence of numerous instruments functioning as natural acoustic elements and careful attention to sound quality in the room's design, provide an ideal setting for experiencing the full range of tonal colors and dynamic contrasts in her program.

This evening offers a rare opportunity to experience art music in an environment that celebrates musical culture in all its dimensions. The combination of Mitritsa's artistry, carefully selected repertoire, and Thyrathen's unique atmosphere creates an event for those who appreciate music in its most refined forms. For listeners seeking alternatives to larger concert halls, this intimate setting provides a chance to discover how venue and performance can create something greater than the sum of their parts.`,

  "34c697828f22d3a0": `Taylor Swift Night arrives at Death Disco with a Halloween twist, combining pop music celebration with costume creativity and seasonal spookiness in one of Athens' most distinctive and edgy nightlife venues. This showgirl Halloween edition transforms the typical tribute night format into a theatrical experience where attendees become active participants in the spectacle through elaborate costumes inspired by Swift's iconic eras, music video aesthetics, and Halloween themes merged into creative mashups. Death Disco's reputation for edgy atmosphere, excellent sound system specifically tuned for pop music's production qualities, and crowds that embrace theatrical expression makes it the perfect environment for this fusion of pop culture celebration and seasonal Halloween fun.

The event curates Taylor Swift's extensive and evolution-spanning catalog, from her country beginnings with songs like "Love Story" and "You Belong With Me" through her evolution into pop superstardom with albums like "1989" and "Reputation," to her recent alternative-influenced work on "folklore" and "evermore." DJs familiar with both Swift's discography and club dynamics ensure that each song connects with the crowd at the right moment, creating those magical instances when an entire room sings along to beloved tracks like "Shake It Off" or "Anti-Hero." The Halloween element adds an extra layer of excitement and creative possibilities, encouraging imaginative interpretations of Swift's various visual eras combined with spooky aesthetics—from Reputation-era gothic looks merged with vampire themes to folklore's cottagecore mysticism reimagined with Halloween's witch aesthetic.

Death Disco's reputation for hosting themed events that transcend typical club nights and become immersive experiences makes it an ideal setting for this celebration. The venue's production capabilities allow for visual elements that enhance the Taylor Swift atmosphere, including projections of iconic music video moments, era-specific decorations, and Halloween touches that create photo-worthy backdrops, while maintaining the energy and sound quality that keeps people dancing throughout the night. The showgirl edition emphasis suggests a focus on glamour, performance, and theatrical self-expression, encouraging attendees to embrace their most creative costume interpretations and participate in the event's overall aesthetic.

For Swift fans seeking a unique way to celebrate their appreciation for her music beyond simply listening to albums, this Halloween-themed night offers community connection through shared musical love and creative expression. The event creates space for both dedicated Swifties who know every lyric and casual fans who simply enjoy her hits to mingle in a social environment designed for celebration rather than judgment.`,

  "adb4fb5c59991873": `Barcelona Gipsy balKan Orchestra brings their explosive and joyful fusion of Balkan traditions, rebetiko, klezmer, and manouche jazz to Greece for two special concerts, performing in Thessaloniki on Thursday, October 24th at WE and in Athens on Friday, October 25th. This celebrated ensemble has built an international reputation for creating musical experiences that honor traditional forms with deep respect and knowledge while infusing them with contemporary energy, virtuosic musicianship, and cross-cultural innovation that reveals unexpected connections between musical traditions. Their approach to Balkan and Mediterranean music traditions demonstrates how heritage sounds can speak powerfully to modern audiences when performed with both authenticity and creative vision that refuses to treat tradition as museum piece.

The orchestra's repertoire draws from the rich musical traditions of the Balkans—including Serbian, Romanian, Bulgarian, and Macedonian folk music—Greece's rebetiko heritage with its connections to urban working-class culture and Asia Minor musical influences, Jewish klezmer with its celebratory and melancholic dimensions, and the sophisticated jazz of Django Reinhardt's manouche style developed in the Romani communities of France. This combination creates a sound that is simultaneously rooted in deep historical knowledge and thrillingly current in its execution, with virtuosic instrumental performances that showcase each tradition's distinctive characteristics—the driving brass of Balkan orchestras, the modal sophistication of rebetiko, klezmer's clarinet wizardry, and manouche guitar techniques—while revealing their unexpected connections and shared roots in Romani musical culture.

Live performances by Barcelona Gipsy balKan Orchestra are known for their ability to transform venues into celebratory spaces where musical boundaries dissolve and audiences from different backgrounds find common ground through rhythm and melody. The group's stage presence combines formal musicianship and technical precision with the spontaneous joy and direct emotional communication of street performance traditions, encouraging audience participation and dancing while maintaining the artistic integrity of their arrangements. Their shows often feature extended improvisational sections where individual musicians' virtuosity shines, creating unique moments that make each performance special and ensuring that no two concerts are exactly alike.

For lovers of world music, traditional Greek sounds, Balkan brass energy, or anyone curious about how musical traditions can be honored while being reimagined for contemporary contexts, these two-city concerts offer extraordinary opportunities. Whether you're familiar with Balkan brass bands, rebetiko's melancholic beauty, klezmer's celebratory spirit, or Django's jazz innovation, Barcelona Gipsy balKan Orchestra's performances promise evenings of musical discovery and joyful celebration.`,

  "c6f6d9220ce15dc6": `Pasxalis returns to Theatro Alsos for an all-time party that promises unforgettable Friday nights throughout the season, starting October 24th and continuing every Friday thereafter. This residency at one of Athens' most beloved entertainment venues brings together Pasxalis' dynamic performance style, versatile vocal capabilities, and natural showmanship with the theatrical setting, excellent acoustics, and comfortable atmosphere that have made Alsos a destination for quality live music and entertainment. Joining him are the DeuxCaDanse duo, with Stelios Mac on guitar and vocals adding another dimension to the musical experience and creating opportunities for collaborative moments, musical dialogues, and versatile programming that elevates the evening beyond typical solo performances.

The "All Time Party" concept suggests a celebration of beloved songs spanning multiple eras, styles, and moods, creating a musical journey through time that connects different generations of music lovers while maintaining energy and festive atmosphere throughout the evening. Pasxalis' performance approach combines strong vocal abilities across different styles with engaging stage presence and natural ability to create rapport with audiences, making them feel like participants rather than passive observers. His ability to read the room's energy, adjust song selection and pacing accordingly, and maintain spontaneity while delivering polished performance ensures that each Friday night maintains freshness while building the consistent quality and recognizable character that creates loyal followings and word-of-mouth recommendations.

Theatro Alsos' winter venue provides an intimate yet professional setting that enhances the party atmosphere while maintaining high production standards in sound, lighting, and overall presentation. The venue's reputation for hosting successful music residencies throughout Athens' entertainment history speaks to its ability to create comfortable, engaging environments where performers and audiences can connect authentically without pretension or excessive formality. The recurring Friday night format allows the event to build momentum over the season, with returning attendees becoming part of an evolving community that shares inside jokes and favorite moments, while new visitors discover what makes these nights special and often return themselves.

The collaboration with DeuxCaDanse adds instrumental sophistication to the vocal performances, with guitar work that can support songs with rhythm and harmony, complement vocals with melodic lines, or dialogue with the main performances through improvisation and musical conversation. For those seeking a reliable Friday night destination that combines quality music with festive atmosphere and social possibilities, Pasxalis' Theatro Alsos residency offers an appealing alternative to both impersonal club scenes and overly formal concert settings.`,

  "122e52c948047bb1": `Encardia presents a Tarantella Party at Theatre of the NO, featuring an ensemble of accomplished Greek musicians including Natalia Kotsani and Vangelis Papageorgiou as lead artists, along with Michalis Kontaxakis, Kostas Konstantatos, Giorgos Ntanis, Konstantina Kalkani, and Anastasia. This evening celebrates the tarantella, a traditional Italian folk dance and music form known for its rapid tempo, infectious rhythms, distinctive 6/8 time signature patterns, and historical connections to healing rituals, communal celebration, and southern Italian cultural identity. The Theatre of the NO's context as an English-speaking theatre adds an international dimension to this celebration of Mediterranean musical traditions, making the event accessible to both Greek audiences and the international community living in or visiting Athens.

The tarantella's history combines folklore, music, dance, and cultural mythology in ways that have fascinated audiences for centuries. Originally associated with southern Italian traditions, particularly from regions like Puglia and Campania, and the mythical bite of the tarantula spider that supposedly could only be cured through frenzied dancing until the poison was expelled through sweat, the tarantella has evolved into a celebration of life, community resilience, and the healing power of music and collective movement. Encardia's presentation likely explores both traditional forms preserved through generations of folk musicians and contemporary interpretations that reveal the music's continued relevance and adaptability to modern performance contexts while respecting its cultural roots.

The ensemble format allows for rich textural possibilities and dynamic range, with multiple musicians contributing to the layered rhythms, interweaving melodic lines, and call-and-response patterns characteristic of traditional tarantella music. The performance creates opportunities for both structured arrangements that showcase the ensemble's technical coordination and improvisational moments that reflect the music's historical connection to spontaneous community gatherings where professional and amateur musicians would play together. The emphasis on "party" in the title suggests an interactive element beyond passive concert attendance, potentially inviting audience participation through clapping, dancing, or other forms of engagement that honor the tarantella's origins in communal celebration rather than formal presentation.

For those interested in Mediterranean musical traditions, folk music from diverse cultures, ethnomusicology in accessible formats, or simply seeking an evening of energetic, life-affirming music that celebrates cultural heritage, this Tarantella Party offers something unique. The combination of skilled musicians who respect the tradition, a distinctive venue that supports innovative programming, and a musical tradition rich in history and vitality creates potential for an evening that is simultaneously educational and entertaining.`,

  "6da67f12872f3e2b": `Koupes returns to Stavros tou Notou Club for a special live performance on Friday, October 24th, bringing their distinctive rock sound to one of Athens' most respected and historically significant music venues. This appearance marks another chapter in the ongoing relationship between the band and this iconic space, which has long served as a home for quality rock music in the Greek capital, supporting both established acts and emerging artists who prioritize musical integrity over commercial considerations. The Club's intimate setting, excellent acoustics carefully maintained over years of operation, and reputation for hosting meaningful performances make it an ideal environment for experiencing Koupes' dynamic sound and emotional honesty, which has earned them a dedicated following within Greece's alternative rock scene.

Koupes has built their reputation on creating rock music that honors the genre's traditions and emotional directness while incorporating elements that reflect contemporary Greek musical sensibilities, cultural references that resonate with local audiences, and lyrical concerns addressing current experiences rather than generic rock clichés. Their songwriting balances melodic accessibility that invites listeners into the songs with instrumental sophistication that rewards repeated listening, featuring guitar work that ranges from atmospheric textures creating sonic landscapes to powerful riffs that drive songs forward, supported by tight rhythm section work that provides both solid foundation and dynamic flexibility. The band's live shows are known for creating genuine connection with audiences through both musical intensity and between-song communication, transforming concert spaces into communities united by shared musical experience and mutual respect between performers and listeners.

Stavros tou Notou's Club space has become legendary within Athens' music scene for its commitment to presenting quality live music in an environment that respects both performers' artistic needs and audiences' listening experience without the compromises often imposed by purely commercial considerations. The venue's sound system, regularly maintained and operated by experienced sound engineers who understand rock music's specific requirements, and acoustic design refined through decades of hosting performances ensure that the nuances of rock performance come through clearly, allowing audiences to appreciate both the power and the subtlety in the music. The intimate capacity creates an atmosphere where performers and audience share space in ways that larger venues cannot replicate, making for more intense and memorable experiences where individual audience members feel personally addressed by the performance.

This October performance offers fans both familiar with Koupes' catalog and newcomers to their music an opportunity to experience Greek rock at its most authentic. Whether you're a longtime follower or curious newcomer, this evening promises genuine rock music that speaks honestly.`,

  "0f44f38b34a407f6": `Doros Dimosthenous presents "Eixa Foni, Tin Piran Ta Poulia" (I Had a Voice, the Birds Took It) at Stavros tou Notou Plus on Friday, October 24th, offering an intimate evening of art music that explores the intersection of Greek musical traditions, contemporary classical composition, and artistic expression that defies easy categorization. This evocatively titled performance suggests a program dealing with themes of voice, nature, loss, transformation, and the relationship between human and non-human expression—universal subjects approached through Dimosthenous' distinctive musical lens and the refined aesthetic sensibilities that characterize art music traditions at their most thoughtful and emotionally resonant.

Stavros tou Notou Plus provides an ideal setting for this type of performance, with its focus on acoustic excellence, intimate atmosphere that allows subtle musical nuances to be fully appreciated, and audience composition that values artistic substance over superficial entertainment. The venue has established itself as a destination for discerning music lovers seeking alternatives to mainstream entertainment, consistently programming artists who prioritize artistic integrity, meaningful communication through their work, and respect for audiences' intelligence and capacity for focused listening. The space's design facilitates direct connection between performer and audience without physical or psychological barriers, creating an environment where music can be experienced with full attention and minimal distraction from external factors.

Dimosthenous' approach to art music likely draws from diverse influences within Greek musical heritage—including Byzantine chant traditions, folk melodies from various regional traditions, and art music composers who have worked with Greek materials—while incorporating contemporary compositional techniques, extended performance practices, and conceptual frameworks that address current artistic concerns. The poetic nature of the title "I Had a Voice, the Birds Took It" suggests a program that explores the relationship between human and natural expression through music and possibly text, perhaps touching on themes of influence and inspiration, the ways voices—both literal and metaphorical—are transformed through creative processes and encounters with other forms of expression, and questions about originality and borrowing that concern all artists.

This conceptual depth adds layers of meaning to the musical experience, inviting audiences to engage both emotionally through the music's sonic beauty and intellectually with the ideas being explored. For lovers of art music, Greek contemporary composition, experimental performance practices, or anyone seeking musical experiences that offer more than entertainment and engage with substantial artistic questions, this evening promises depth and artistic vision that respects audience intelligence.`,

  "2aa796c58f29e049": `Theodore brings his highly anticipated album "FIRE" to Eightball Club on October 24th, 2025, for a special release show that promises to be one of the most exciting and talked-about rock events of the season. This performance marks the official live debut of new material that represents the evolution of Theodore's artistic vision over recent years, offering audiences the first opportunity to experience these songs in their intended format—performed with full energy, proper volume, and the kind of intensity that only happens in front of a live crowd invested in the music and the moment. Eightball Club's reputation as a premier rock venue in Athens, known for supporting artists who prioritize musical integrity and for hosting performances that become memorable events rather than just another gig, makes it the perfect setting for this important milestone in Theodore's career.

The "FIRE" album represents a bold creative statement, with Theodore pushing his sound into new territories while maintaining the core elements that have earned him respect within Greece's rock community—honest songwriting, instrumental skill, and refusal to compromise artistic vision for commercial considerations. The release show will feature these new compositions performed with the intensity, precision, and emotional commitment that characterize Theodore's best work, likely including extended arrangements not possible within album format constraints, improvisational moments that can only happen in live settings, and the kind of between-song communication that reveals the artist behind the music. The band's extensive preparation for this release show, including rehearsals focused on translating studio arrangements to live performance while leaving room for spontaneity, suggests a performance that honors the album's studio vision while unleashing the additional energy and immediacy that comes from direct audience interaction and real-time musical decisions.

Eightball Club has established itself as Athens' go-to venue for rock music that demands to be experienced at proper volume, with a sound system specifically designed and regularly updated for guitar-driven music, bass frequencies that you feel physically, and acoustic design that ensures clarity even at high volumes. The venue's atmosphere—equal parts professional and rebellious, welcoming newcomers while maintaining the respect for music that longtime patrons expect—reflects the spirit of rock music at its most authentic. The relatively intimate capacity ensures that this release show will feel like a special event rather than an anonymous concert, with early adopters and dedicated fans sharing the experience of hearing these new songs for the first time in their proper context, creating memories and community connections that extend beyond the music itself.

For followers of Theodore's previous work, this release show represents a chance to witness his artistic growth firsthand and hear how his sound has evolved while maintaining recognizability.`,

  "0f32d63de4011289": `Giannis Ploutarxos and Katerina Kakosaiou join forces at Vergina Theatro within the Regency Casino Thessaloniki complex, bringing two powerful voices and established stage presences together for an evening of popular Greek music that promises high-energy entertainment, memorable performances, and the kind of atmosphere that characterizes Greek popular music at its most celebratory. This pairing represents a strategic collaboration between established artists who command devoted followings individually, creating an event that offers both the familiarity of beloved solo repertoires that fans know by heart and the excitement of collaborative moments between two distinctive performers whose vocal styles and stage personas complement each other.

Ploutarxos has built a career spanning decades on delivering emotionally charged performances of contemporary Greek popular music, with a vocal style that connects directly with audiences through its power, expressiveness, and ability to convey the emotional depths of songs about love, loss, celebration, and life's various chapters. His repertoire includes both original material written specifically for his voice and distinctive interpretations of popular songs by other artists, all delivered with the commitment, energy, and showmanship that have made him one of the most reliable draws in Greek popular entertainment across generations of fans. Kakosaiou brings her own distinctive vocal qualities, different performance approach, and complementary energy to the evening, adding variety to the program and creating opportunities for duets, musical dialogues, and contrasting moments that enhance the overall evening's entertainment value and pacing.

Vergina Theatro at Regency Casino Thessaloniki provides a professional entertainment environment with production values that ensure both vocal performances and overall show presentation meet the high standards that audiences expect from established artists and premium venues. The venue's capacity and design create an atmosphere suited to popular music entertainment, with sight lines ensuring all attendees feel connected to the performance, acoustics optimized for vocal clarity, and lighting that enhances the theatrical aspects of the show. The casino setting adds an element of occasion and luxury to the evening, positioning this as a complete entertainment experience rather than simply a concert, with opportunities for dining and other activities that make the evening feel special.

For fans of contemporary Greek popular music, this double billing offers substantial value, with two accomplished performers sharing an evening and likely appearing together for special collaborative moments that create unique experiences unavailable at solo concerts. The combination of Ploutarxos' established presence and Kakosaiou's contributions creates a program with built-in variety, ensuring sustained energy and interest throughout the performance while allowing each artist to showcase their individual strengths.`,

  "3c35455c7b9ab170": `Enastron presents the season's premiere with two of Greek popular music's biggest stars—Natasa Theodoridou and Sakis Rouvas—sharing the stage starting October 24th in what promises to be one of the most spectacular and talked-about entertainment events of the year. This collaboration represents a major event in Greek entertainment, bringing together two artists whose careers have defined different aspects of contemporary Greek popular music over the past decades, whose combined star power commands national attention, and whose pairing creates anticipation for what will likely be one of the season's most memorable shows. Their combined experience, professionalism, and commitment to quality entertainment, along with the prestige of the Enastron venue with its history of hosting major productions, create high expectations for a show that delivers on multiple levels.

Theodoridou's career has been marked by emotional depth, vocal sophistication, and ability to bring artistic credibility to popular music forms while maintaining broad audience appeal across different demographics. Her ability to interpret songs with genuine feeling rather than mere technical competence has earned her respect across generations of Greek music lovers and critical acclaim from those who might otherwise dismiss popular music. Rouvas brings a different but complementary energy and skill set to the pairing, with his background in performance, entertainment spectacle, and international competition experience creating moments of excitement, visual interest, and crowd engagement that balance Theodoridou's more introspective approach. Together, they offer audiences variety in style, energy, and approach while maintaining the consistently high quality standards expected from artists at their career levels who have proven themselves repeatedly.

The Enastron venue has established itself as the destination for major entertainment events in Greece, with production capabilities that support elaborate staging, sophisticated lighting design, high-quality sound systems, and the kind of theatrical elements that transform concerts into complete entertainment experiences. The venue's commitment to creating comprehensive shows rather than simple performances means this premiere will feature more than just two singers performing their hits—it represents a carefully crafted show that incorporates visual elements, choreography, costume changes, and production values that match the caliber of the headliners and create an experience worthy of the ticket price.

For fans of Greek popular music, this season opener at Enastron represents an event not to be missed—a rare chance to see two major artists sharing a stage in a venue designed to showcase entertainment at its highest level, creating memories that will be discussed long after the curtain falls.`,

  "6d7a2629859c7bc8": `Chryspa takes the stage at Kafetheatro for a live performance that brings dynamic vocal talent, engaging stage presence, and contemporary Greek music to one of Athens' most charming intimate venues that successfully bridges cafe culture and theatrical performance space. The Kafetheatro setting creates an atmosphere that combines casual socializing with focused entertainment, allowing audiences to enjoy quality performance in a relaxed environment that feels welcoming rather than intimidating, comfortable rather than stuffy, and social rather than isolated. This venue's approach to programming consistently emphasizes artistic quality while maintaining accessibility, making it a favorite among Athenians seeking alternatives to both mainstream clubs with their emphasis on DJs and dancing, and formal concert halls with their rigid conventions and acoustic focus.

Chryspa's live performances are characterized by vocal power that can fill the space without electronic assistance, emotional directness that creates genuine connection with audiences, and a repertoire that spans contemporary Greek popular music and potentially includes material from various related traditions and personal interpretations of beloved songs. The intimate setting of Kafetheatro allows for a different kind of performance than larger venues permit—one where subtle vocal nuances can be appreciated by attentive listeners, where direct eye contact between performer and audience creates moments of recognition and connection, and where direct communication between performer and audience becomes possible and even expected. This creates opportunities for spontaneous moments, genuine interaction, and the kind of connection that makes live music experiences memorable beyond simply hearing songs performed.

The venue's cafe element means audiences can enjoy refreshments, coffee, drinks, and light food while experiencing the performance, creating a social dimension that enhances the entertainment value and makes the evening feel relaxed rather than formal. Kafetheatro's design balances these dual functions effectively, ensuring that the performance space maintains acoustic quality and respectful quiet during performances while the cafe elements contribute to overall atmosphere and comfort without creating distraction or interfering with the musical experience. This format has proven popular with audiences seeking evenings out that combine multiple pleasures—good music, comfortable surroundings, opportunities for conversation with friends or companions, and refreshments—creating complete experiences rather than single-purpose outings.

For those familiar with Chryspa's work, this Kafetheatro appearance offers a chance to experience her vocals in an intimate setting that highlights their qualities, allows appreciation of nuance and dynamics, and creates personal connection. For newcomers, it provides an accessible introduction to a talented performer in a venue that makes quality entertainment feel approachable rather than intimidating or exclusive.`,

  "cac17d1648d1679b": `"Violontsela Ektos Programmatos" (Cellos Off Program) brings Anna Chrysanthou and Despoina Spanou to Caja De Musica for an evening that explores the expressive possibilities of the cello in ways that transcend conventional classical recital formats, predetermined programs, and the formal conventions that sometimes create barriers between performers and audiences. This musical event promises performances that showcase the cello's remarkable versatility and emotional range, with repertoire selections that may include classical masterworks by Bach, Brahms, and other composers who understood the instrument's potential, alongside contemporary compositions by living creators pushing boundaries, and possibly improvisational elements that allow the performers to respond to the moment and the audience's energy rather than adhering strictly to predetermined structures.

The "off program" concept suggests spontaneity and artistic freedom, with the performers choosing music that speaks to them in the moment, responding to the audience's reactions and the evening's developing atmosphere, and allowing for the kind of flexibility that can lead to unexpected moments of beauty and connection rather than merely executing a predetermined plan. The cello occupies a unique place among musical instruments, with a tonal range that spans from deep bass notes that resonate in the chest to high singing melodies that soar above, and expressive capabilities that can evoke profound emotional responses from joy to melancholy. Two cellos performing together create opportunities for rich harmonic textures where the instruments blend into unified sound, contrapuntal dialogues where they converse with each other in musical conversation, and moments of stunning unison that demonstrate the instrument's power when voices join together.

Chrysanthou and Spanou bring their individual artistic voices, technical abilities, and musical personalities to this collaboration, creating a program that likely balances moments of technical virtuosity that showcase years of training and practice with passages of lyrical beauty that touch the heart directly, and emotional depth that speaks to universal human experiences. The performance creates opportunities for both structured arrangements that demonstrate careful rehearsal and preparation and improvisational moments that reflect the music's historical connection to spontaneous creation and the performers' ability to listen to each other and respond in real time.

Caja De Musica provides an ideal setting for this type of musical exploration, with its commitment to presenting innovative programming that challenges conventional boundaries, an environment that prioritizes acoustic quality and intimate audience connection, and atmosphere that encourages focused listening while maintaining a welcoming quality that makes classical and contemporary instrumental music accessible to diverse audiences.`,

  "65ef3f9919461fdd": `Evridiki presents "La Boheme" at the legendary Half Note Jazz Club for a three-night engagement running Friday, October 24th through Sunday, October 26th, bringing one of Greece's most distinctive vocal artists to Athens' premier jazz venue for an interpretation of classic material reimagined through Evridiki's unique artistic lens, sophisticated musical understanding, and commitment to authentic expression. The title "La Boheme" evokes both Puccini's beloved opera with its romantic story of artists living in poverty while pursuing their creative dreams, and the broader romantic tradition of bohemian artistic life that has inspired creators across disciplines for generations. This suggests a program that explores themes of love, art, creative passion, the sacrifices artists make for their work, and the passionate pursuit of creative expression regardless of material circumstances.

Evridiki has built her career on artistic integrity, vocal excellence that respects the music she interprets, and bringing sophisticated interpretative skills to diverse material without being constrained by genre limitations or commercial pressures. Her approach to classic works often reveals new dimensions in familiar material through fresh arrangements, unexpected tempo choices, and interpretive decisions that honor the original while bringing contemporary relevance. She finds meaning and emotional truth in songs and compositions that others might treat as museum pieces or mere nostalgia, demonstrating how great material remains vital when approached with genuine artistry. The Half Note setting—with its decades-long history of presenting jazz and sophisticated popular music, commitment to acoustic quality, and atmosphere that supports nuanced vocal performance—provides ideal conditions for this type of artistic exploration and respectful reinterpretation.

The three-night engagement format allows Evridiki and her accompanying musicians to develop the program over multiple performances, potentially varying arrangements based on what worked in previous shows, exploring different aspects of the material each evening as they grow more comfortable and find new possibilities, and allowing the artistic vision to evolve naturally through performance rather than being fixed in a single interpretation. This creates value for audience members who might attend multiple shows, as each evening offers slightly different experiences while maintaining the core artistic vision. Half Note's intimate capacity ensures that every seat offers direct connection to the performance, making each evening feel like a special event rather than just another show, and allowing audiences to appreciate subtle vocal techniques and emotional nuances that might be lost in larger venues.

For lovers of vocal artistry, thoughtful interpretations of classic material that reveal new meanings, or anyone who appreciates how established works can be given new life through creative reimagining and deep respect, these Half Note performances promise artistic substance. Evridiki's commitment to authentic expression means audiences can expect performances driven by genuine artistic vision.`,

  "d236297aa4806b91": `AUX welcomes Berlin-based Colombian DJ and producer Adriana Lopez for a Friday night showcase on October 24th, bringing one of techno's most respected and uncompromising artists to Athens for an evening of forward-thinking electronic music that pushes boundaries while honoring techno's fundamental purpose of creating transformative dancefloor experiences. Lopez, known for her regular appearances at Berghain—widely considered the world's most iconic techno club—and her work with PoleGroup, represents techno at its most artistically serious and musically innovative, refusing to compromise for commercial considerations or mainstream acceptance. Joining her are accomplished local talents Adam Des collaborating with Indelekt, along with a.metz working with Cirkle, creating a lineup that demonstrates AUX's commitment to programming electronic music that challenges and rewards adventurous listeners willing to surrender to sustained immersion.

Lopez's approach to DJing draws from techno's rich history spanning Detroit's pioneering innovations, Berlin's dark aesthetic developments, and contemporary experimental approaches, while pushing toward the genre's future possibilities through unexpected selections and juxtapositions. Her sets are known for building gradually rather than delivering instant gratification, creating journeys through sound that reward sustained attention and full immersion in the music rather than casual listening. She constructs tension and release over extended periods, allowing tracks to develop fully, mixing with technical precision, and understanding how to pace an extended set for maximum impact. The support from local talents Adam Des, Indelekt, a.metz, and Cirkle—all respected figures in Athens' underground electronic music scene—ensures a full night of quality electronic music programmed with careful attention to flow, with each artist contributing their perspective while maintaining the evening's cohesive vision and building toward Lopez's headlining performance.

AUX Club has established itself as Athens' destination for serious electronic music, with a sound system designed specifically for techno and related genres by engineers who understand the music's requirements for bass weight, clarity across frequencies, and power that you feel physically. The venue's commitment to quality programming and its focus on the music rather than superficial club elements, bottle service, or celebrity DJ bookings has earned it respect within both local and international electronic music communities. The space's design prioritizes the dancefloor experience above all else, with lighting and visuals that enhance rather than distract from the music's immersive qualities, creating an environment where the music itself remains the primary focus.

For techno enthusiasts and those curious about electronic music's cutting edge where innovation happens, this night offers a rare opportunity to experience an internationally recognized artist whose work shapes the genre's evolution in Athens' most dedicated electronic music venue.`,

  "5fc667638147f2fd": `Baro Passo brings their debut album "BACTERIA" to ILION Plus on October 25th for a live presentation that promises explosive energy, intense musical dynamics, and the kind of passionate performance that comes from artists eager to share work they've poured creative effort into creating. This Athens-based band makes their recorded debut with material that demands to be experienced in live format, where the full power of their sound can be properly unleashed without the compression and constraints of recorded formats, and where the interaction between performers and audience creates something beyond what's possible in studio settings. The album presentation format suggests a performance focused primarily on new material rather than mixing old and new, giving audiences the first opportunity to experience these songs as intended—performed with live energy, proper volume, and the kind of intensity that only happens in front of an engaged crowd invested in discovering new music.

The album title "BACTERIA" suggests music that deals with themes of spread and contagion, infection of ideas or emotions, persistence and resilience of small things that cannot be eliminated, and transformation through invasion or contamination—concepts that can be explored through both lyrical content addressing contemporary anxieties about contagion literal and metaphorical, and musical intensity that creates visceral rather than merely intellectual responses. Baro Passo's approach appears to embrace rock music's tradition of addressing challenging subjects through powerful sound, creating music that engages both intellectually through its conceptual concerns and viscerally through sonic impact and dynamic range. Their commitment to "energy and powerful musical tensions" as stated in their description indicates a band unafraid to explore dynamic extremes, moving between controlled quieter passages that create anticipation and explosive release that provides cathartic satisfaction and physical impact.

ILION Plus has emerged as an important venue for emerging bands building their careers and established acts seeking alternatives to mainstream entertainment spaces that prioritize commercial considerations over artistic integrity. The venue's focus on quality sound reproduction, respectful treatment of both performers who are given proper technical support and audiences who are trusted to appreciate adventurous music, and commitment to supporting the alternative music community has made it a favorite within Athens' alternative music scene among both artists and audiences. The space's capacity and design work well for rock performances that demand proper volume for full impact and clear sound reproduction across frequency ranges, ensuring that Baro Passo's debut album receives the sonic treatment it deserves and that their vision translates fully to the audience.

For fans of contemporary rock music with edge, substance, and willingness to take creative risks, this debut album presentation represents a chance to discover a band at the beginning of what could be a significant career trajectory.`,

  "5b6035ede348ef4c": `Trouf embarks on the "STRADA NERA" (Black Road) Tour 2025, bringing his new album to venues across Greece in a comprehensive tour that promises to be one of the most significant Greek music events of the season, demonstrating both the ambitious scope of the project and Trouf's commitment to connecting directly with audiences throughout the country rather than only performing in major urban centers. This multi-city tour demonstrates respect for fans across different regions and recognition that meaningful audiences exist beyond Athens and Thessaloniki. The album title's evocative imagery—a black road suggesting journeys through dark territories literal or metaphorical—hints at music that explores darker themes emotionally, takes listeners on journeys through challenging emotional and sonic territories, or addresses difficult subjects that other artists might avoid for commercial considerations.

Trouf has built his reputation on creating music that defies easy categorization and refuses to fit neatly into predetermined genre boxes, drawing from diverse influences including Greek musical traditions, contemporary production approaches, international sounds filtered through personal vision, and songwriting sensibilities that speak to current experiences rather than recycling inherited formulas. His work often incorporates elements of Greek musical traditions—modal scales, rhythmic patterns, instrumental timbres—reimagined through contemporary production approaches and songwriting sensibilities that address contemporary life rather than nostalgic recreation. The live presentation of "STRADA NERA" will likely feature full band arrangements that expand on the album's studio vision, creating opportunities for improvisation that reveals new dimensions in the material, extended sections that allow songs to develop beyond album constraints, and the kind of spontaneous moments that make concerts memorable and distinguish live performance from recorded versions.

The tour format allows different communities across Greece to experience this new work, reflecting a democratic approach to music presentation that values audiences outside major urban centers and recognizes that passionate music lovers exist everywhere. Each performance will likely adapt to its specific venue's acoustic properties and local audience's energy, creating unique experiences while maintaining the core integrity of the material and Trouf's artistic vision. The multiple dates also allow the performances to evolve over time as the tour progresses, with earlier shows informing later interpretations as Trouf and his musicians grow more comfortable with the material in live settings, discover what works and what might need adjustment, and respond to feedback both explicit and implicit from audiences.

For fans of contemporary Greek music that pushes boundaries while remaining rooted in authentic expression and respect for tradition, this tour represents essential events worth traveling to experience. Album tours create special atmospheres, with audiences eager to hear new material they may have heard recorded but never experienced live.`,

  "05f953b5ae4761ff": `Lunar brings her album "All About Image" to Piraeus Club Academy on October 25th, presenting new material in one of greater Athens' most dynamic music venues that has established itself as an important alternative to central Athens locations for quality live music across genres. This live performance marks the official introduction of Lunar's latest artistic statement to Athenian audiences, offering the first opportunity to experience these songs in their proper context—performed live with full energy, production values that support the artistic vision, and the kind of intensity and presence that only happens in performance before audiences invested in the moment. The album title "All About Image" suggests explorations of appearance versus reality, perception and how we're seen by others, authenticity in an age of curated social media personas, and the roles we play in contemporary visual culture where everyone performs identity through Instagram filters and carefully selected posts.

Lunar's artistic approach appears to embrace contemporary music's possibilities without being limited by genre boundaries, potentially incorporating elements from pop, electronic music, alternative rock, and other traditions while maintaining a cohesive artistic vision and recognizable aesthetic. Her work likely addresses the tensions between surface and substance, between how we present ourselves through carefully curated images and who we actually are in unguarded moments, between authentic expression and performed identity—universal themes made more complex and urgent by social media culture and constant visual documentation of daily life. The live presentation will reveal how these conceptual concerns translate into performance and musical arrangements, creating opportunities for visual elements, stage design, and theatrical presentation to complement sonic components and reinforce thematic concerns.

Piraeus Club Academy has established itself as a versatile venue capable of hosting diverse musical styles from rock to electronic to pop while maintaining consistently high production standards in sound quality, lighting capabilities, and overall presentation. The Academy's location in Piraeus—Athens' historic port city with its own distinct identity and cultural character—gives it a separate identity from central Athens venues, attracting audiences seeking alternatives to familiar entertainment districts and creating its own community of regulars. The venue's capacity and technical capabilities ensure that Lunar's vision for this album presentation can be fully realized, with sound systems capable of handling contemporary production's bass weight and frequency range, lighting that supports theatrical elements, and spatial design that works for both concert performance and audience comfort.

For those interested in contemporary music that engages with current cultural concerns beyond simple entertainment, this album presentation offers substance and conceptual depth. Lunar's willingness to address complex themes through her music suggests an artist committed to creating work that matters beyond commercial success, that attempts to say something meaningful about contemporary experience.`,

  "1fc160c45cbd311c": `Jameson Connects presents an exceptional double bill featuring British singer-songwriter Gizmo Varillas and Greek electronic music innovator Monsieur Minimal at Gagarin 205 on Saturday, October 25th, creating an evening that bridges acoustic singer-songwriter craft and electronic music production excellence. This pairing represents the Jameson Connects series' commitment to creating unexpected musical dialogues and cross-genre conversations, bringing together artists from different genres, backgrounds, and approaches to create evenings that transcend typical concert formats and reveal unexpected connections between seemingly disparate musical traditions. The combination of Varillas' songwriter craft rooted in folk traditions and contemporary sensitivity with Monsieur Minimal's electronic production expertise drawing from Greece's rich tradition of innovative dance music creates a night of diverse musical experiences united by artistic quality, creative vision, and refusal to compromise for commercial considerations.

Gizmo Varillas has built an international following through thoughtful songwriting that blends folk sensibilities and acoustic instrumentation with contemporary production approaches, electronic elements used tastefully, and global influences reflecting his Spanish-British background and extensive travel. His music creates intimate yet expansive songs that address universal themes—love, loss, identity, belonging, displacement—through personal storytelling that connects with audiences across cultural boundaries. His live performances are known for creating emotional connection with audiences through honest delivery free of performance artifice, melodic sophistication that serves songs rather than showcasing technique, and ability to make large rooms feel intimate through direct communication. Monsieur Minimal brings a completely different aesthetic—electronic music that draws from Greece's rich tradition of innovative dance music production while incorporating international influences from minimal techno to progressive house, creating tracks that work on dancefloors while containing enough detail and development to reward home listening.

Gagarin 205 provides the ideal setting for this ambitious and thoughtfully curated programming, with a sound system capable of doing justice to both acoustic singer-songwriter material requiring clarity and detail and electronic music's bass-heavy dynamics requiring power and precision across frequency ranges. The venue's reputation for hosting diverse musical styles while maintaining consistent quality and respect for both music and audiences has made it one of Athens' most respected concert spaces. The Jameson Connects branding indicates production values and curation that go beyond typical concert presentation, creating complete experiences that honor both the music and the audience's intelligence.

For music lovers who resist genre boundaries and appreciate artistic excellence across styles, this evening offers remarkable value and opportunities for discovery. The pairing of Varillas and Monsieur Minimal creates opportunities to discover new music while enjoying familiar sounds, with each artist's set illuminating different aspects of contemporary music's possibilities.`
};

// Process all events
async function processAll() {
  const batchPath = join(import.meta.dir, "../data/enrichment-batches/batch-2-of-13.json");
  const events: RawEvent[] = JSON.parse(readFileSync(batchPath, "utf-8"));

  stats.total = events.length;

  console.log("🎵 Processing Batch 2 Event Enrichment (20 events)");
  console.log("━".repeat(60));

  for (const event of events) {
    const enrichedDescription = enrichments[event.id];

    if (!enrichedDescription) {
      stats.failed++;
      stats.results.push({
        title: event.title,
        wordCount: 0,
        status: "❌ No enrichment found"
      });
      console.log(`❌ ${event.title}`);
      console.log(`   Status: No enrichment found`);
      console.log("");
      continue;
    }

    const wordCount = countWords(enrichedDescription);
    const aiContext = {
      enriched: true,
      wordCount,
      enrichedAt: new Date().toISOString(),
      batch: 2
    };

    try {
      const success = updateEventEnrichment(event.id, enrichedDescription, aiContext);

      if (success) {
        stats.successful++;
        stats.totalWords += wordCount;
        stats.results.push({
          title: event.title,
          wordCount,
          status: "✅ Success"
        });
        console.log(`✅ ${event.title}`);
        console.log(`   Words: ${wordCount} | Status: Success`);
      } else {
        stats.failed++;
        stats.results.push({
          title: event.title,
          wordCount: 0,
          status: "❌ Database update failed"
        });
        console.log(`❌ ${event.title}`);
        console.log(`   Status: Database update failed`);
      }
    } catch (error) {
      stats.failed++;
      stats.results.push({
        title: event.title,
        wordCount: 0,
        status: `❌ Error: ${error}`
      });
      console.log(`❌ ${event.title}`);
      console.log(`   Error: ${error}`);
    }
    console.log("");
  }

  // Final summary
  console.log("━".repeat(60));
  console.log("📊 BATCH 2 PROCESSING SUMMARY");
  console.log("━".repeat(60));
  console.log(`Total events processed: ${stats.successful + stats.failed}/${stats.total}`);
  console.log(`Successfully enriched: ${stats.successful}`);
  console.log(`Failed: ${stats.failed}`);
  console.log(`Total words generated: ${stats.totalWords.toLocaleString()}`);
  console.log(`Average words per description: ${Math.round(stats.totalWords / stats.successful)}`);
  console.log("━".repeat(60));

  // Detailed results
  console.log("\n📋 DETAILED RESULTS:");
  console.log("━".repeat(60));
  for (const result of stats.results) {
    console.log(`${result.status} | ${result.title}`);
    if (result.wordCount > 0) {
      console.log(`   ${result.wordCount} words`);
    }
  }
}

processAll().catch(console.error);
